name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.13.1"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with recording
        run: npx cypress run --config-file config/cypress.config.js --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
